# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8wV96WarctO0ElrakZTTaheqE4fOHY6
"""

import pandas as pd
import plotly.express as px

df=pd.read_csv("Genes.csv")

df

df.info()

df.describe()

df.dtypes

df.columns



df['user_id'].isnull().sum()

df1 = df.dropna(subset=['user_id'])

df1

df1['user_type'] = df1['user_id'].apply(lambda x: 'Free user' if x.startswith('unknown') else 'Logged In')

df1

rename_mapping = {df1.columns[i]: f"col_{i}" for i in range(1, 110)}
df1.rename(columns=rename_mapping, inplace=True)

df1

df1.columns

df2 = df1.iloc[:, 1:-2]

df2

all_values = df2.values.flatten()
all_values = pd.Series(all_values).dropna()

all_values_counts=all_values.value_counts()

all_values_counts

user_type_counts = df1['user_type'].value_counts()

user_type_counts

api_hit_sum = df1['userInfo.apiHitCount'].sum()

api_hit_sum

#!pip install streamlit

import streamlit as st

st.title("Data Dashboard")

# Filter for 'user_type'
user_type_filter = st.sidebar.multiselect(
    "Filter by User Type",
    options=df1['user_type'].unique(),
    default=df1['user_type'].unique()
)

# Apply filter to df1
filtered_df1 = df1[df1['user_type'].isin(user_type_filter)]

# Update all_value_counts and api_hit_sum based on filter
filtered_col3 = filtered_df1['col3'] if 'col3' in filtered_df1 else []
all_values_counts = pd.Series(filtered_col3).value_counts()
api_hit_sum = filtered_df1['userInfo.apiHitCount'].sum()

# Display details on the dashboard
st.subheader("Flattened df2 Value Counts (Bar Chart)")
if not all_values_counts.empty:
    bar_chart = px.bar(
        all_values_counts,
        x=all_values_counts.index,
        y=all_values_counts.values,
        labels={"x": "Value", "y": "Count"},
        title="All Value Counts"
    )
    st.plotly_chart(bar_chart)

st.subheader("User Type Value Counts (Pie Chart)")
if not filtered_df1['user_type'].value_counts().empty:
    pie_chart = px.pie(
        filtered_df1['user_type'].value_counts(),
        names=filtered_df1['user_type'].value_counts().index,
        values=filtered_df1['user_type'].value_counts().values,
        title="User Type Distribution"
    )
    st.plotly_chart(pie_chart)

st.subheader("Total API Hit Count")
st.write(api_hit_sum)

# Optional: Display filtered df1
st.subheader("Filtered df1")
st.write(filtered_df1)





